---
name: Deploy a Prefect flow
author: PrefectHQ
description: Deploy a flow from a project by creating a Prefect deployment.
branding:
  icon: upload-cloud
  color: blue

inputs:
  additional-args:
    description:
      Any additinal arguments that need to be passed to
      the prefect deployment run in a space separated format.
      i.e - `--variable foo=bar -t 1.0.0 --cron "* * * * *"`.
    required: false

  entrypoint:
    description:
      The path to a flow entrypoint within a project,
      in format `./path/to/file.py:flow_func_name`.
    required: true

  prefect-api-key:
    description:
      API Key to authenticate with Prefect.
    required: true

  prefect-workspace:
    description:
      Full handle of workspace, in format
      `<account_handle>/<workspace_handle>`.
    required: true

  requirements-file-path:
    description:
      Path to requirements files to correctly install
      dependencies for your Prefect flow(s).
    required: false
    default: ./requirements.txt


runs:
  using: composite
  steps:
    - id: install-prefect-locally
      shell: bash
      run: pip install -q prefect

    - id: install-local-requirements
      run: pip install -r ${{ inputs.requirements-file-path }}
      shell: bash

    - id: prefect-cloud-login
      run: |
        prefect cloud login \
        --key ${{ inputs.prefect-api-key }} \
        --workspace ${{ inputs.prefect-workspace }}
      shell: bash

    - id: prefect-deploy
      run: |
        prefect deploy ${{ inputs.entrypoint }} \
         ${{ inputs.additional-args }}
      shell: bash
